<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "<title>food website  </title>";
echo "<!--Web Guru-->";
echo "<!-- font awesome cdn link  -->";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">";
echo "";
echo "<!-- custom css file link  -->";
echo "<link rel=\"stylesheet\" href=\"style.css\">";
echo "";
echo "</head>";
echo "";
echo "<body>";
echo "";
echo "<!-- Hero Section with Video Background -->";
echo "<section class=\"hero\">";
echo "<video autoplay muted loop playsinline class=\"bg-video\">";
echo "<source src=\"video/food.mp4\" type=\"video/mp4\" />";
echo "Your browser does not support the video tag.";
echo "</video>";
echo "";
echo "<div class=\"hero-content\">";
echo "<h1>zippy</h1>";
echo "<h2>India’s #1 <br> food delivery </h2>";
echo "<p>Experience fast & easy online delivery on the Zippy </p>";
echo "";
echo "";
echo "</div>";
echo "</section>33";
echo "";
echo "<!-- header section starts  -->";
echo "";
echo "<header>";
echo "";
echo "<a href=\"#\" class=\"logo\"><i class=\"fas fa-utensils\"></i>Zippy</a>";
echo "";
echo "";
echo "<div id=\"menu-bar\" class=\"fas fa-bars\"></div>";
echo "";
echo "<nav class=\"navbar\">";
echo "<a href=\"index.html\">home</a>";
echo "<a href=\"speciallity.html\">speciality</a>";
echo "<a href=\"popular.html\">popular</a>";
echo "<a href=\"gallery.html\">gallery</a>";
echo "<a href=\"review.html\">review</a>";
echo "<a href=\"order.html\">order</a>";
echo "<a href=\"account.html\">account</a>";
echo "<a href=\"cart.html\" class=\"cart-icon\">";
echo "<i class=\"fas fa-shopping-cart\"></i>";
echo "<span id=\"cart-count\">0</span>";
echo "</a>";
echo "";
echo "</nav>";
echo "";
echo "</header>";
echo "";
echo "<!-- header section ends -->";
echo "";
echo "";
echo "";
echo "<!-- home section starts -->";
echo "<section class=\"home\" id=\"home\">";
echo "<div class=\"content\">";
echo "<h3>Fresh, Fast & Flavorful</h3>";
echo "<p>Satisfy your cravings with our chef-crafted dishes made with the freshest ingredients. Ready in minutes, delivered with care, and sure to delight your taste buds.</p>";
echo "<a href=\"order.html\" class=\"btn\">Order Now</a>";
echo "</div>";
echo "";
echo "<div class=\"image\">";
echo "<img src=\"images/home-img.png\" alt=\"Delicious food image\">";
echo "</div>";
echo "</section>";
echo "<!-- home section ends -->";
echo "";
echo "";
echo "<!-- steps section starts  -->";
echo "";
echo "<div class=\"step-container\">";
echo "";
echo "<h1 class=\"heading\">how it <span>works</span></h1>";
echo "";
echo "<section class=\"steps\">";
echo "";
echo "<div class=\"box\">";
echo "<img src=\"images/step-1.jpg\" alt=\"\">";
echo "<h3>choose your favorite food</h3>";
echo "</div>";
echo "<div class=\"box\">";
echo "<img src=\"images/step-2.jpg\" alt=\"\">";
echo "<h3>free and fast delivery</h3>";
echo "</div>";
echo "<div class=\"box\">";
echo "<img src=\"images/step-3.jpg\" alt=\"\">";
echo "<h3>easy payments methods</h3>";
echo "</div>";
echo "<div class=\"box\">";
echo "<img src=\"images/step-4.jpg\" alt=\"\">";
echo "<h3>and finally, enjoy your food</h3>";
echo "</div>";
echo "";
echo "</section>";
echo "";
echo "</div>";
echo "";
echo "<!-- steps section ends -->";
echo "";
echo "";
echo "";
echo "<!-- footer section  -->";
echo "";
echo "<section class=\"footer\">";
echo "";
echo "<div class=\"share\">";
echo "<a href=\"#\" class=\"btn\">facebook</a>";
echo "<a href=\"#\" class=\"btn\">twitter</a>";
echo "<a href=\"#\" class=\"btn\">instagram</a>";
echo "<a href=\"#\" class=\"btn\">pinterest</a>";
echo "<a href=\"#\" class=\"btn\">linkedin</a>";
echo "</div>";
echo "";
echo "<h1 class=\"credit\"> Created by <span> Web Guru </span> | All rights reserved </h1>";
echo "";
echo "</section>";
echo "";
echo "<!-- scroll top button  -->";
echo "<a href=\"#home\" class=\"fas fa-angle-up\" id=\"scroll-top\"></a>";
echo "";
echo "<!-- loader  -->";
echo "<div class=\"loader-container\">";
echo "<img src=\"images/loader.gif.gif\" alt=\"\">";
echo "</div>";
echo "";
echo "";
echo "<!--Web Guru-->";
echo "";
echo "";
echo "";
echo "";
echo "<!-- custom js file link  -->";
echo "<script src=\"script.js\"></script>";
echo "";
echo "";
echo "";
echo "</body>";
echo "";
echo "</html>";
?>